---
title: "R Notebook"
output: html_notebook
---

## Fixed X
```{r}
## X
simulation_3_noise$init_X <- (test_data_noise$generated_data$proportions / rowSums(test_data_noise$generated_data$proportions)) %*% t(simulation_3_noise$R)

## D
N <- ncol(simulation_3_noise$V_row)
M <- nrow(simulation_3_noise$V_row)
#simulation_3_noise$init_D_h <- ginv(t(simulation_3_noise$init_X)) %*% simulation_3_noise$A
#simulation_3_noise$init_D_h <- simulation_3_noise$init_D_h * (M/N)
#simulation_3_noise$init_Omega <- t(simulation_3_noise$new_samples_points[c(41,42,43),])
#simulation_3_noise$init_D_w <- ginv(simulation_3_noise$init_Omega) %*% simulation_3_noise$B
#simulation_3_noise$init_D_h <- simulation_3_noise$init_D_w * (N/M)
```


```{r}
## Random Omega
init_basis_cols <- sample(ncol(simulation_3_noise$V_column), simulation_3_noise$cell_types)
init_basis_ <- simulation_3_noise$V_column[, init_basis_cols]
simulation_3_noise$init_Omega <- simulation_3_noise$S %*% init_basis_
```

```{r}
simulation_3_noise$init_D_w <- ginv(simulation_3_noise$init_Omega) %*% simulation_3_noise$B
simulation_3_noise$init_D_h <- simulation_3_noise$init_D_w * (N/M)
```



```{r}
simulation_3_noise$coef_der_Omega <- 1e-9
simulation_3_noise$coef_hinge_W <- 20
simulation_3_noise$errors_statistics <- NULL
V__ <- simulation_3_noise$S %*% simulation_3_noise$V_row %*% t(simulation_3_noise$R)

simulation_3_noise$X <- simulation_3_noise$init_X
simulation_3_noise$D_w <- simulation_3_noise$init_D_w
simulation_3_noise$Omega <- simulation_3_noise$init_Omega
simulation_3_noise$W_ <- t(simulation_3_noise$S) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1])
count_neg_basis <- sum(simulation_3_noise$W_ < -1e-10)

simulation_3_noise$D_h <- simulation_3_noise$init_D_h
simulation_3_noise$H_ <- simulation_3_noise$X %*% simulation_3_noise$R
simulation_3_noise$full_proportions <- diag(simulation_3_noise$D_h[,1]) %*% simulation_3_noise$H_
count_neg_props <- sum(simulation_3_noise$full_proportions < -1e-10)

cnt <- 0

error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
lambda_error <-
  simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
beta_error <-
  simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega)
D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
prev_error <-
  error_ + lambda_error + beta_error + D_h_error + D_w_error

simulation_3_noise$errors_statistics <-
  rbind(
    simulation_3_noise$errors_statistics,
    c(
      cnt,
      0,
      1,
      1,
      1,
      error_,
      lambda_error,
      D_h_error,
      beta_error,
      D_w_error,
      prev_error,
      count_neg_props,
      count_neg_basis
    )
  )
```

```{r}
toPlot <- as.data.frame(simulation_3_noise$V_row %*% t(simulation_3_noise$R))
colnames(toPlot) <- c("X","Y","Z")
colnames(simulation_3_noise$init_X) <- c("X","Y","Z")
plt1 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(simulation_3_noise$init_X), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_props / (simulation_3_noise$cell_types*N),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r}
toPlot <- as.data.frame(t(simulation_3_noise$S %*% simulation_3_noise$V_column))
colnames(toPlot) <- c("X","Y","Z")
rownames(simulation_3_noise$init_Omega) <- c("X","Y","Z")
plt2 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(t(simulation_3_noise$init_Omega)), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_basis / (simulation_3_noise$cell_types*M),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r, fig.width=8, fig.height=3}
grid.arrange(plt1,plt2,nrow=1)
```

```{r}
head(simulation_3_noise$errors_statistics)
```

```{r}
simulation_3_noise$global_iterations <- 10000

pb <- progress_bar$new(
        format = "Optimization [:bar] :percent eta: :eta",
        total = simulation_3_noise$global_iterations, clear = FALSE, width= 60)
for (t in seq(1,length.out=simulation_3_noise$global_iterations)) {
  der_X <- -2*(t(diag(simulation_3_noise$D_w[,1])) %*% t(simulation_3_noise$Omega) %*% (V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X))
  der_X <- der_X + simulation_3_noise$coef_hinge_H * hinge_der_proportions(simulation_3_noise$X %*% simulation_3_noise$R, simulation_3_noise$R) #+ simulation_3_noise$coef_pos_D_h * simulation_3_noise$D_h %*% t(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A)
  der_X_f <- der_X #/ sqrt(sum(der_X^2))
  der_X_f[,1] <- 0
  simulation_3_noise$X <- simulation_3_noise$X #- (simulation_3_noise$coef_der_X*der_X_f)

  simulation_3_noise$H_ <- simulation_3_noise$X %*% simulation_3_noise$R
  
  simulation_3_noise$full_proportions <- diag(simulation_3_noise$D_h[,1]) %*% simulation_3_noise$H_
  count_neg_props <- sum(simulation_3_noise$full_proportions < -1e-10)
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,1,0,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  for (j in 1:100) {
    mult_D <-  ((t(simulation_3_noise$Omega) %*% V__ %*% t(simulation_3_noise$X)) / (t(simulation_3_noise$Omega) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X %*% t(simulation_3_noise$X)))
    simulation_3_noise$D_w <- matrix(diag(diag(simulation_3_noise$D_w[,1]) * mult_D),nrow=simulation_3_noise$cell_types,ncol=1)
    simulation_3_noise$D_w <- (simulation_3_noise$D_w / sum(simulation_3_noise$D_w)) * M
    simulation_3_noise$D_h <- simulation_3_noise$D_w * (N/M)
  }
  
  
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,1,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  der_Omega <- -2*(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X) %*% t(simulation_3_noise$X) %*% t(diag(simulation_3_noise$D_w[,1]))
  
  der_Omega <- der_Omega + simulation_3_noise$coef_hinge_W * simulation_3_no_noise$hinge_der_basis(t(simulation_3_no_noise$S)%*%simulation_3_noise$Omega, simulation_3_no_noise$S) + simulation_3_noise$coef_pos_D_w * (simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_no_noise$B) %*% t(simulation_3_noise$D_w)
  der_Omega_f <- der_Omega #/ sqrt(sum(der_Omega^2))
  der_Omega_f[1,] <- 0
  simulation_3_noise$Omega <- simulation_3_noise$Omega - (simulation_3_noise$coef_der_Omega*der_Omega_f)
  
  simulation_3_noise$W_ <- t(simulation_3_noise$S) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1])
  count_neg_basis <- sum(simulation_3_noise$W_ < -1e-10)
          
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,0,1,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  for (j in 1:100) {
    mult_D <-  ((t(simulation_3_noise$Omega) %*% V__ %*% t(simulation_3_noise$X)) / (t(simulation_3_noise$Omega) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X %*% t(simulation_3_noise$X)))
    simulation_3_noise$D_w <- matrix(diag(diag(simulation_3_noise$D_w[,1]) * mult_D),nrow=simulation_3_noise$cell_types,ncol=1)
    simulation_3_noise$D_w <- (simulation_3_noise$D_w / sum(simulation_3_noise$D_w)) * M
    simulation_3_noise$D_h <- simulation_3_noise$D_w * (N/M)
  }
  
  
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,1,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  pb$tick()
}
```

```{r}
toPlot <- as.data.frame(simulation_3_noise$V_row %*% t(simulation_3_noise$R))
colnames(toPlot) <- c("X","Y","Z")
colnames(simulation_3_noise$X) <- c("X","Y","Z")
plt1 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(simulation_3_noise$X), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_props / (simulation_3_noise$cell_types*N),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r}
toPlot <- as.data.frame(t(simulation_3_noise$S %*% simulation_3_noise$V_column))
colnames(toPlot) <- c("X","Y","Z")
rownames(simulation_3_noise$Omega) <- c("X","Y","Z")
plt2 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(t(simulation_3_noise$Omega)), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_basis / (simulation_3_noise$cell_types*M),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r, fig.width=8, fig.height=3}
grid.arrange(plt1,plt2,nrow=1)
```

```{r}
colnames(simulation_3_noise$errors_statistics) <- c("idx","iteration","is_X","is_D","is_Omega",
                                                    "deconv_error","lamdba_error","D_h_error",
                                                    "beta_error","D_w_error","total_error",
                                                    "neg_proportions","neg_basis")
View(simulation_3_noise$errors_statistics)
```

```{r, fig.width=10, fig.height=6}
toPlot <- melt(tail(data.frame(simulation_3_noise$errors_statistics[,c("iteration","is_Omega","deconv_error","lamdba_error","beta_error","D_h_error","D_w_error","total_error")]),1000) %>% filter(is_Omega==1),id.vars="iteration",measure.vars = c("deconv_error", "lamdba_error","beta_error","D_h_error","D_w_error","total_error"))
plt <- ggplot(toPlot,aes(x=iteration,y=value,color=variable)) +
  geom_point(size=0.5) +
  geom_line() + theme_minimal()
#ggplotly(plt)
plt
```

```{r, fig.width=10, fig.height=6}
toPlot <- melt(data.frame(simulation_3_noise$errors_statistics[,c("iteration","is_Omega","total_error")]) %>% filter(is_Omega==1),id.vars="iteration",measure.vars = c("total_error"))
plt <- ggplot(toPlot,aes(x=iteration,y=value,color=variable)) +
  geom_point(size=0.5) +
  geom_line() + theme_minimal()
#ggplotly(plt)
plt
```

```{r}
#simulation_3_noise$coef_der_Omega <- 1e-07
simulation_3_noise$global_iterations <- 10000

pb <- progress_bar$new(
        format = "Optimization [:bar] :percent eta: :eta",
        total = simulation_3_noise$global_iterations, clear = FALSE, width= 60)
for (t in seq(nrow(simulation_3_noise$errors_statistics)+1,length.out=simulation_3_noise$global_iterations)) {
  der_X <- -2*(t(diag(simulation_3_noise$D_w[,1])) %*% t(simulation_3_noise$Omega) %*% (V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X))
  der_X <- der_X + simulation_3_noise$coef_hinge_H * hinge_der_proportions(simulation_3_noise$X %*% simulation_3_noise$R, simulation_3_noise$R) + simulation_3_noise$coef_pos_D_h * simulation_3_noise$D_h %*% t(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A)
  der_X_f <- der_X #/ sqrt(sum(der_X^2))
  der_X_f[,1] <- 0
  simulation_3_noise$X <- simulation_3_noise$X #- (simulation_3_noise$coef_der_X*der_X_f)

  simulation_3_noise$H_ <- simulation_3_noise$X %*% simulation_3_noise$R
  
  simulation_3_noise$full_proportions <- diag(simulation_3_noise$D_h[,1]) %*% simulation_3_noise$H_
  count_neg_props <- sum(simulation_3_noise$full_proportions < -1e-10)
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,1,0,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  for (j in 1:100) {
    mult_D <-  ((t(simulation_3_noise$Omega) %*% V__ %*% t(simulation_3_noise$X)) / (t(simulation_3_noise$Omega) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X %*% t(simulation_3_noise$X)))
    simulation_3_noise$D_w <- matrix(diag(diag(simulation_3_noise$D_w[,1]) * mult_D),nrow=simulation_3_noise$cell_types,ncol=1)
    #simulation_3_noise$D_w <- simulation_3_noise$D_w * mult_D
    simulation_3_noise$D_w <- (simulation_3_noise$D_w / sum(simulation_3_noise$D_w)) * M
    simulation_3_noise$D_h <- simulation_3_noise$D_w * (N/M)
  }
  #print(sum(diag(mult_D)))
  
  
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,1,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  der_Omega <- -2*(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X) %*% t(simulation_3_noise$X) %*% t(diag(simulation_3_noise$D_w[,1]))
  
  der_Omega <- der_Omega + simulation_3_noise$coef_hinge_W * simulation_3_no_noise$hinge_der_basis(t(simulation_3_no_noise$S)%*%simulation_3_noise$Omega, simulation_3_no_noise$S) + simulation_3_noise$coef_pos_D_w * (simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_no_noise$B) %*% t(simulation_3_noise$D_w)
  der_Omega_f <- der_Omega #/ sqrt(sum(der_Omega^2))
  der_Omega_f[1,] <- 0
  simulation_3_noise$Omega <- simulation_3_noise$Omega - (simulation_3_noise$coef_der_Omega*der_Omega_f)
  
  simulation_3_noise$W_ <- t(simulation_3_noise$S) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1])
  count_neg_basis <- sum(simulation_3_noise$W_ < -1e-10)
          
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,0,1,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  for (j in 1:100) {
    mult_D <-  ((t(simulation_3_noise$Omega) %*% V__ %*% t(simulation_3_noise$X)) / (t(simulation_3_noise$Omega) %*% simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X %*% t(simulation_3_noise$X)))
    simulation_3_noise$D_w <- matrix(diag(diag(simulation_3_noise$D_w[,1]) * mult_D),nrow=simulation_3_noise$cell_types,ncol=1)
    #simulation_3_noise$D_w <- simulation_3_noise$D_w * mult_D
    simulation_3_noise$D_w <- (simulation_3_noise$D_w / sum(simulation_3_noise$D_w)) * M
    simulation_3_noise$D_h <- simulation_3_noise$D_w * (N/M)
  }
  #print(sum(diag(mult_D)))
  
  
  
  error_ <- norm(V__ - simulation_3_noise$Omega %*% diag(simulation_3_noise$D_w[,1]) %*% simulation_3_noise$X,"F")^2
  lambda_error <- simulation_3_noise$coef_hinge_H * simulation_3_noise$hinge(simulation_3_noise$X %*% simulation_3_noise$R)
  beta_error <- simulation_3_noise$coef_hinge_W * simulation_3_noise$hinge(t(simulation_3_noise$S) %*% simulation_3_noise$Omega) 
  D_h_error <-
  simulation_3_noise$coef_pos_D_h * norm(t(simulation_3_noise$X)%*%simulation_3_noise$D_h-simulation_3_noise$A,"F")^2
  D_w_error <-
  simulation_3_noise$coef_pos_D_w * norm(simulation_3_noise$Omega%*%simulation_3_noise$D_w-simulation_3_noise$B,"F")^2
          
  new_error <- error_ + lambda_error + beta_error + D_h_error + D_w_error
          
  cnt <- cnt + 1
  simulation_3_noise$errors_statistics <- rbind(simulation_3_noise$errors_statistics,c(cnt,t,0,1,0,
                                                                   error_,
                                                                   lambda_error,
                                                                   D_h_error,
                                                                   beta_error,
                                                                   D_w_error,
                                                                   new_error,
                                                                   count_neg_props,
                                                                   count_neg_basis))
  
  pb$tick()
}
```

```{r}
colnames(simulation_3_noise$errors_statistics) <- c("idx","iteration","is_X","is_D","is_Omega",
                                                    "deconv_error","lamdba_error","D_h_error",
                                                    "beta_error","D_w_error","total_error",
                                                    "neg_proportions","neg_basis")
#View(simulation_3_noise$errors_statistics)
```

```{r}
toPlot <- as.data.frame(simulation_3_noise$V_row %*% t(simulation_3_noise$R))
colnames(toPlot) <- c("X","Y","Z")
colnames(simulation_3_noise$X) <- c("X","Y","Z")
plt1 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(simulation_3_noise$X), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_props / (simulation_3_noise$cell_types*N),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r}
toPlot <- as.data.frame(t(simulation_3_noise$S %*% simulation_3_noise$V_column))
colnames(toPlot) <- c("X","Y","Z")
rownames(simulation_3_noise$Omega) <- c("X","Y","Z")
plt2 <- ggplot(toPlot, aes(x=Y, y=Z)) +
  geom_point() + 
  geom_polygon(data=as.data.frame(t(simulation_3_noise$Omega)), fill=NA, color = "green") +
  annotate("text",  x=Inf, y = Inf, label = paste0(round(count_neg_basis / (simulation_3_noise$cell_types*M),4)*100,"%"), vjust=1, hjust=1) +
  theme_minimal() #+ coord_cartesian(x=c(-0.1,0.1),y=c(-0.1,0.15))
```

```{r, fig.width=8, fig.height=3}
grid.arrange(plt1,plt2,nrow=1)
```

```{r}
View(simulation_3_noise$errors_statistics)
```

```{r, fig.width=10, fig.height=6}
toPlot <- melt(data.frame(tail(simulation_3_noise$errors_statistics[,c("iteration","is_Omega","deconv_error","lamdba_error","beta_error","D_h_error","D_w_error","total_error")],1000)) %>% filter(is_Omega==1),id.vars="iteration",measure.vars = c("deconv_error", "lamdba_error","beta_error","D_h_error","D_w_error","total_error"))
plt <- ggplot(toPlot,aes(x=iteration,y=value,color=variable)) +
  geom_point(size=0.5) +
  geom_line() + theme_minimal()
plt
#ggplotly(plt)
```

```{r, fig.width=10, fig.height=6}
toPlot <- melt(data.frame(tail(simulation_3_noise$errors_statistics[,c("iteration","is_Omega","total_error")],1000)) %>% filter(is_Omega==1),id.vars="iteration",measure.vars = c("total_error"))
plt <- ggplot(toPlot,aes(x=iteration,y=value,color=variable)) +
  geom_point(size=0.5) +
  geom_line() + theme_minimal()
plt
#ggplotly(plt)
```



